# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d32afbbb30657a940a158d5ddb7dd68c52295c8629ec70d9b61a63b8a4323ced96f55678a08e652bfa7f343ce0575436a96a430c996db0be8b83e9eff0d54c57

test:
  secret_key_base: 629d79c7e0fd547e1323a3e3149ae0733f190cfef95e3695c722ca94f5baf7ebe89ff0b995dccac41af01cfbb1c8d4fe3b47e07005835029db0a66529d897f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
